import { useEffect, useState } from 'react';
import { Plus, Pencil, Trash2 } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import { formatCurrency } from '../../lib/utilities/currency';

const empty = { name:'', amount:'', category_id:'', period_start:'', period_end:'' };
export default function BudgetPage({ user }) {
  const [budgets,setBudgets]=useState([]); const [categories,setCategories]=useState([]); const [form,setForm]=useState(empty); const [editing,setEditing]=useState(null); const [message,setMessage]=useState('');
  const load=async()=>{ const [b,c]=await Promise.all([supabase.from('finance_budgets').select('*, finance_categories(name)').eq('user_id',user.id).order('period_end',{ascending:true}),supabase.from('finance_categories').select('id,name').eq('user_id',user.id).in('type',['expense','both']).order('name')]); setBudgets(b.data||[]); setCategories(c.data||[]); };
  useEffect(()=>{load()},[user.id]);
  const save=async(e)=>{e.preventDefault();setMessage('');const payload={user_id:user.id,name:form.name.trim(),amount:Number(form.amount)||0,category_id:form.category_id||null,period_start:form.period_start,period_end:form.period_end};const r=editing?await supabase.from('finance_budgets').update(payload).eq('id',editing).eq('user_id',user.id):await supabase.from('finance_budgets').insert(payload);if(r.error)return setMessage(r.error.message);setForm(empty);setEditing(null);setMessage('Anggaran berhasil disimpan.');load()};
  const remove=async(id)=>{if(!confirm('Hapus anggaran ini?'))return;const r=await supabase.from('finance_budgets').delete().eq('id',id).eq('user_id',user.id);if(r.error)setMessage(r.error.message);else load()};
  return <div className="page-content"><header className="page-header"><div><p className="eyebrow">KEUANGAN</p><h1>Anggaran</h1><p className="muted">Tetapkan batas pengeluaran berdasarkan periode dan kategori.</p></div></header><div className="two-column"><form className="panel form-panel" onSubmit={save}><div className="panel-heading"><h3>{editing?'Edit Anggaran':'Tambah Anggaran'}</h3></div><label>Nama<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required placeholder="Belanja Bulanan"/></label><label>Nominal<input type="number" min="0" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} required/></label><label>Kategori<select value={form.category_id} onChange={e=>setForm({...form,category_id:e.target.value})}><option value="">Semua kategori</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="form-row"><label>Mulai<input type="date" value={form.period_start} onChange={e=>setForm({...form,period_start:e.target.value})} required/></label><label>Selesai<input type="date" value={form.period_end} onChange={e=>setForm({...form,period_end:e.target.value})} required/></label></div><button className="primary-button" type="submit"><Plus size={18}/>{editing?'Simpan Perubahan':'Tambah Anggaran'}</button>{editing&&<button type="button" className="secondary-button" onClick={()=>{setEditing(null);setForm(empty)}}>Batal</button>}{message&&<div className="alert">{message}</div>}</form><section className="panel"><div className="panel-heading"><h3>Daftar Anggaran</h3></div>{budgets.length?budgets.map(b=><div className="budget-item" key={b.id}><div className="row-between"><div><strong>{b.name}</strong><small className="muted">{b.finance_categories?.name||'Semua kategori'} · {b.period_start} s/d {b.period_end}</small></div><strong>{formatCurrency(b.amount)}</strong></div><div className="actions"><button onClick={()=>{setEditing(b.id);setForm({name:b.name||'',amount:String(b.amount||0),category_id:b.category_id||'',period_start:b.period_start||'',period_end:b.period_end||''})}} aria-label="Edit"><Pencil size={16}/></button><button onClick={()=>remove(b.id)} aria-label="Hapus"><Trash2 size={16}/></button></div></div>):<div className="empty-state">Belum ada anggaran.</div>}</section></div></div>;
}
